'use client'

import { useState } from 'react'
import Image from 'next/image'
import { ArrowDown, ArrowUpRight, Camera, Menu as MenuIcon, MessageCircle, Music2, Phone, Star, Users, X } from 'lucide-react'

const whatsapp = 'https://wa.me/593983202196'
const maps = 'https://www.google.com/maps/search/?api=1&query=Vicente+Pacheco+412%2C+Ricaurte%2C+Cuenca%2C+Ecuador'
const socials = [
  { label: 'Instagram', href: 'https://www.instagram.com/cafeterialas5esquinas', icon: Camera },
  { label: 'Facebook', href: 'https://www.facebook.com/cafeterialas5esquinas/?locale=es_LA', icon: Users },
  { label: 'TikTok', href: 'https://www.tiktok.com/@las.5.esquinas', icon: Music2 },
  { label: 'WhatsApp', href: whatsapp, icon: MessageCircle },
]

const menu = {
  Menú: [['Tamal de pollo','$0,90'],['Humita','$1,00'],['Humita frita','$1,35'],['Quimbolito','$1,00'],['Tortilla de yuca','$1,25'],['Tortilla de choclo','$1,00'],['Emborrajados','$2,00'],['Tostada sencilla','$1,25'],['Tostada mixta','$1,50']],
  Especialidades: [['Bolón','$1,25','queso o chicharrón'],['Bolón Mixto','$1,50','queso + chicharrón'],['Bolón de Queso o Chicharrón + Carne','$2,50'],['Bolón Mixto + Carne','$2,75'],['Bolón Especial','$2,75','queso o chicharrón + tocino + mozzarella + ensalada + salsas'],['Bolón Especial','$3,00','queso o chicharrón + tocino + mozzarella + ensalada + huevo + salsas'],['Bolón Especial Mixto','$3,25','mixto + tocino + mozzarella + huevo + ensalada + salsas'],['Tigrillo con Queso o Chicharrón','$2,75'],['Tigrillo con Queso o Chicharrón + Carne','$3,25'],['Tigrillo Completo','$4,00','carne + chorizo + huevo + queso']],
  'Comida rápida': [['Hamburguesa especial','$3,00'],['Hamburguesa normal','$2,50'],['Hot Dog de 32 cm','$3,25'],['Hot Dog normal','$2,00'],['Cubano','$2,50'],['Papipollo','$2,50'],['Arroz con pollo broaster','$3,00'],['Seco de carne','$3,00'],['Salchipapa','$1,25']],
  'Alitas de pollo': [['Combo 1','$4,25','5 alitas + papas + tomate + salsas · BBQ, Miel & Mostaza, Maracuyá, Búfalo'],['Combo 2','$8,00','10 alitas + papas + tomate + salsas · BBQ, Miel & Mostaza, Maracuyá, Búfalo'],['Combo 3','$11,50','15 alitas + papas + tomate + salsas · BBQ, Miel & Mostaza, Maracuyá, Búfalo'],['Combo 4','$15,00','20 alitas + papas + tomate + salsas · BBQ, Miel & Mostaza, Maracuyá, Búfalo'],['Combo 5','$19,25','25 alitas + papas + tomate + salsas · BBQ, Miel & Mostaza, Maracuyá, Búfalo']],
  'Bebidas calientes': [['Tinto (Café Pasado)','$0,80'],['Chocolate','$1,50'],['Colada Morada','$1,50'],['Morocho','$1,25'],['Aguas aromáticas','', 'Horchata · Manzanilla · Cedrón · Anís']],
  Extras: [['Huevo frito','$0,75'],['Presa de pollo','$1,75'],['Porción de arroz','$2,00'],['Porción de papa','$1,50'],['Porción de carne','$1,25'],['Porción de queso','$0,50'],['Arroz dorado con chuleta','$4,50']],
} as const
type Category = keyof typeof menu

function Brand({ light = false }: { light?: boolean }) { return <a href="#inicio" className={`brand ${light ? 'brand-light' : ''}`} aria-label="Cafetería Las 5 Esquinas, inicio"><span className="brand-mark">5</span><span className="font-serif text-[15px] font-semibold leading-[0.92] tracking-[-.02em]">Cafetería<br /><em className="not-italic text-primary">Las 5 Esquinas</em></span></a> }

function SocialRail() { return <div className="social-rail" aria-label="Redes sociales">{socials.map(({ label, href, icon: Icon }) => <a key={label} href={href} target="_blank" rel="noreferrer" aria-label={label} title={label} className={label === 'WhatsApp' ? 'social-whatsapp' : ''}><Icon size={18} strokeWidth={1.8} /></a>)}</div> }

function Header() { const [open, setOpen] = useState(false); return <header className="site-header"><div className="header-inner"><Brand light /><nav className="hidden items-center gap-7 md:flex" aria-label="Navegación principal"><a href="#presentacion">Nosotros</a><a href="#especialidades">Especialidades</a><a href="#menu">Menú</a><a href="#ubicacion">Ubicación</a></nav><button className="mobile-toggle md:hidden" onClick={() => setOpen(!open)} aria-label={open ? 'Cerrar menú' : 'Abrir menú'}>{open ? <X /> : <MenuIcon />}</button></div>{open && <nav className="mobile-nav md:hidden"><a onClick={() => setOpen(false)} href="#presentacion">Nosotros</a><a onClick={() => setOpen(false)} href="#especialidades">Especialidades</a><a onClick={() => setOpen(false)} href="#menu">Menú</a><a onClick={() => setOpen(false)} href="#ubicacion">Ubicación</a><a onClick={() => setOpen(false)} href={whatsapp} target="_blank" rel="noreferrer" className="button-primary">Pedir por WhatsApp <ArrowUpRight size={16} /></a></nav>}</header> }

function Hero() { return <section id="inicio" className="hero-full"><Image src="/cafe-editorial.png" alt="Café servido en Cafetería Las 5 Esquinas" fill priority className="hero-photo" sizes="100vw" /><div className="hero-overlay" /><div className="hero-content"><p className="eyebrow hero-eyebrow">Ricaurte · Cuenca, Ecuador</p><h1 className="hero-title font-serif">Cafetería<br /><span>Las 5</span><br /><i>Esquinas</i></h1><p className="hero-copy">Café, comida y antojos para cualquier momento.</p><a href="#menu" className="hero-cta">Menú <ArrowDown size={18} /></a></div><div className="hero-note">Una propuesta gastronómica cercana<br />desde Ricaurte</div></section> }

function Intro() { return <section id="presentacion" className="intro-section"><div className="section-shell intro-grid"><p className="eyebrow">La mesa está servida</p><div><h2 className="display-title">Un lugar para empezar el día, hacer una pausa o resolver el antojo.</h2><p className="body-copy">Una propuesta gastronómica que reúne café, desayunos, especialidades, comida rápida, bebidas y más.</p></div></div></section> }

function Specialties() { const cards = [['Bolón','Tradición que reconforta','/bolon-editorial.png'],['Tigrillo','Un clásico para comenzar','/tigrillo-editorial.png'],['Alitas','Para compartir el antojo','/alitas-editorial.png']]; return <section id="especialidades" className="section-shell specialties"><div className="section-heading"><div><p className="eyebrow">Para elegir sin pensarlo tanto</p><h2 className="display-title">Especialidades</h2></div><a href="#menu" className="link-arrow">Explorar el menú <ArrowUpRight size={16} /></a></div><div className="specialty-grid">{cards.map(([title, desc, src], i) => <article key={title} className={`specialty-card specialty-${i + 1}`}><div className="specialty-image"><Image src={src} alt={`${title}, especialidad de la cafetería`} fill className="object-cover transition duration-700 hover:scale-105" sizes="(max-width: 768px) 100vw, 33vw" /></div><div className="specialty-caption"><h3 className="font-serif">{title}</h3><p>{desc}</p></div></article>)}</div></section> }

function MenuSection() { const [active, setActive] = useState<Category>('Menú'); return <section id="menu" className="menu-section"><div className="section-shell"><div className="menu-intro"><p className="eyebrow text-primary">Hecho para elegir fácil</p><h2 className="display-title">El menú</h2><p className="body-copy">Sabores para cada momento del día, con precios claros y opciones para todos los antojos.</p></div><div className="menu-tabs" role="tablist" aria-label="Categorías del menú">{Object.keys(menu).map(cat => <button key={cat} role="tab" aria-selected={active === cat} onClick={() => setActive(cat as Category)} className={active === cat ? 'active' : ''}>{cat}</button>)}</div><div className="menu-list">{menu[active].map(([name, price, detail]) => <div key={`${name}-${price}`} className="menu-item"><div><h3>{name}</h3>{detail && <p>{detail}</p>}</div>{price && <span>{price}</span>}</div>)}</div><a href={whatsapp} target="_blank" rel="noreferrer" className="button-primary menu-button">Pedir por WhatsApp <ArrowUpRight size={17} /></a></div></section> }

function Reviews() { return <section className="section-shell reviews"><div className="review-heading"><p className="eyebrow">Lo que dicen</p><h2 className="display-title">Una buena razón para volver.</h2></div><div className="review-grid">{[['De las mejores opciones de comida rápida: excelente sabor, tamaño y precio','Camila Garcia'],['Buen lugar para comer una golosina tipo comida rápida, buena atención, buen ambiente y sobretodo buena comida. Muy recomendable','Manuel Valdez']].map(([quote, name]) => <figure key={name} className="review-card"><div className="stars">{[1,2,3,4,5].map(n => <Star key={n} size={15} fill="currentColor" />)}</div><blockquote>“{quote}”</blockquote><figcaption>{name} · 5/5</figcaption></figure>)}</div></section> }

function Location() { return <section id="ubicacion" className="location"><div className="location-image"><Image src="/alitas-editorial.png" alt="Alitas de pollo con papas" fill className="object-cover" sizes="(max-width: 1024px) 100vw, 50vw" /></div><div className="location-copy"><p className="eyebrow">Encuéntranos</p><h2 className="display-title">Las 5 Esquinas</h2><address>Ricaurte - 5 Esquinas<br />Vicente Pacheco 412<br />Cuenca, Ecuador</address><a href={maps} target="_blank" rel="noreferrer" className="button-primary">Cómo llegar <ArrowUpRight size={17} /></a></div></section> }

function Footer() { return <footer id="contacto" className="footer"><div className="section-shell"><div className="footer-top"><div><Brand /><p className="footer-copy">Café, comida y antojos para cualquier momento.</p></div><div className="footer-contact"><a href="tel:0983202196"><Phone size={16} />0983202196</a><a className="button-primary" href={whatsapp} target="_blank" rel="noreferrer">Pedir por WhatsApp <ArrowUpRight size={16} /></a></div></div><div className="footer-bottom"><p>Demo / propuesta comercial no oficial</p><div className="footer-socials">{socials.slice(0, 3).map(({ label, href }) => <a key={label} href={href} target="_blank" rel="noreferrer">{label}</a>)}</div></div></div></footer> }

export function Las5Esquinas() { return <><Header /><main><Hero /><Intro /><Specialties /><MenuSection /><Reviews /><Location /><section className="final-cta"><p className="eyebrow">El antojo ya está decidido</p><h2 className="font-serif">¿Qué se te antoja?</h2><a href={whatsapp} target="_blank" rel="noreferrer" className="button-primary">Pedir por WhatsApp <ArrowUpRight size={17} /></a></section></main><Footer /><SocialRail /></> }
